# Generated by Django 5.1.4 on 2025-01-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0002_ad_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
