# Generated by Django 5.1.4 on 2025-01-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0003_ad_location_ad_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='external_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
