# Generated by Django 5.1.4 on 2025-01-13 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0004_ad_external_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barrel_finder.ad')),
            ],
        ),
    ]
