# Generated by Django 5.1.4 on 2025-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0005_adimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
