# Generated by Django 5.1.4 on 2025-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
