# Generated by Django 5.1.4 on 2025-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0007_ad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
