# Generated by Django 5.1.4 on 2025-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0009_ad_thumb_failed_alter_ad_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clean_description',
            field=models.TextField(null=True),
        ),
    ]
