# Generated by Django 5.1.4 on 2025-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrel_finder', '0010_ad_clean_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
