# Generated by Django 5.1.4 on 2025-01-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='last_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
