# Generated by Django 5.1.4 on 2025-01-09 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_answer_last_answer_answer_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('not_answered', 'not answered'), ('last_answered', 'last answered'), ('invalid', 'invalid'), ('valid', 'valid')], default='not_answered', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
