# Generated by Django 5.1.4 on 2025-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_answer_answered_answer_status_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
