# Generated by Django 5.1.4 on 2025-01-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
    ]
