# Generated by Django 5.1.4 on 2025-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flashcard',
            field=models.TextField(null=True),
        ),
    ]
