# Generated by Django 5.1.4 on 2025-02-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_question_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='flashcard',
        ),
        migrations.AddField(
            model_name='question',
            name='flashcard_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='flashcard_question',
            field=models.TextField(null=True),
        ),
    ]
