# Generated by Django 5.1.4 on 2025-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_question_flashcard_question_flashcard_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flashcard_no',
            field=models.IntegerField(default=0),
        ),
    ]
