# Generated by Django 5.1.4 on 2025-03-02 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_question_flashcard_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('lc', 'PZŁ kandydat'), ('ls', 'PZŁ selekcjoner')], default='lc', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='legal_basis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pzlow_id',
            field=models.IntegerField(null=True),
        ),
    ]
